export const header = [
    {
        id: 1,
        title: "Dashboard",
        link: "/",
        icon: "bx bxs-dashboard",
        role: [],
    },
    {
        id: 2,
        title: "Xodimlar",
        link: "/employees",
        icon: "bx bxs-user-rectangle",
        role: [],
    },
    {
        id: 3,
        title: "O'quvchilar",
        link: "/students",
        icon: "bx bxs-user",
        role: [],
    },
    {
        id: 4,
        title: "Lavozimlar",
        link: "/roles",
        icon: "bx bxs-group",
        role: [],
    },
    {
        id: 4,
        title: "Guruhlar",
        link: "/groups",
        icon: "bx bxs-group",
        role: [],
    },
    {
        id: 5,
        title: "Fanlar",
        link: "/subjects",
        icon: "bx bxs-book-bookmark",
        role: [],
    },
    {
        id: 6,
        title: "Testlar",
        link: "/tests",
        icon: "bx bxs-hourglass-bottom",
        role: [],
    },
    {
        id: 7,
        title: "Natijalar",
        link: "/results",
        icon: "bx bxs-pie-chart-alt-2",
        role: [],
    },
];
